tito/add prettier and eslint
ngareleo/donald pull request #26
Opened 2024-06-12 16:58 UTC by titus-mumo

2024-06-12 17:11 UTC, ngareleo requested changes

2024-06-12 17:11 UTC, ngareleo commented on package.json
> +    "eslint-config-prettier": "^9.1.0",
we should move this to devDependencies

2024-06-12 18:45 UTC, titus-mumo commented on package.json
> +    "eslint-config-prettier": "^9.1.0",
Done ✅

2024-06-13 09:59 UTC, ngareleo commented on package.json
> +    "husky": "^9.0.11",
Husky too, eslint is generally a developer tool and is not used by code running in the server. So all its related dependecies should be put under dev deps

2024-06-17 18:30 UTC, ngareleo approved these changes

2024-06-17 21:03 UTC, merged